name: multi-target-build
on:
  workflow_dispatch:

env:
  PROJECT_NAME: cli_gptr

jobs:
  multi-target-build:

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt install -qq -y musl-tools --no-install-recommends

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Check release Directory for Linux
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          zip --junk-paths gptr-${{ matrix.target }}.zip target/${{ matrix.target }}/release/gptr config/gptr.json config/gptr_predefine.json
          ls -la target/${{ matrix.target }}/release/
      - name: Check release Directory for Mac
        if: matrix.target == 'x86_64-apple-darwin'
        run: |
          zip --junk-paths gptr-${{ matrix.target }}.zip target/${{ matrix.target }}/release/gptr config/gptr.json config/gptr_predefine.json
      - name: Check release Directory for Windows
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          powershell Compress-Archive -Path target/${{ matrix.target }}/release/gptr.exe,config/gptr.json,config/gptr_predefine.json -DestinationPath gptr-${{ matrix.target }}.zip

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.target }}
          path: |
            gptr-${{ matrix.target }}.zip


